name: CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    env:
      DLHUB_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      DLHUB_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9  # Start with the earliest version
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        pip install -r test-requirements.txt
    - name: Lint with flake8
      run: |
        conda install flake8
        flake8 redoxweb/
    - name: Test with pytest
      run: |
        conda install pytest
        pytest redoxweb
